Workflow horizontal extension
joomla-projects/joomla-pythagoras pull request #129
Opened 2016-09-27 13:45 UTC by laoneo

Should illustrate a basic horizontal extension which adds state information to articles.

2016-09-27 15:37 UTC, nibra requested changes
Good starting point!

2016-09-27 15:37 UTC, nibra commented on extensions/Workflow/entities/StateEntity.xml
> +        />
Either adopt label and description, or just omit them.

2016-09-27 15:37 UTC, nibra commented on extensions/Workflow/data/states.csv
> +5,"Under Review"
Remember newline at the end of the file.

2016-09-27 15:37 UTC, nibra commented on extensions/Workflow/ContentType/StateEntity.php
> +}
Ok for now, but should be implemented as a callback for the renderer in the end.

2016-09-27 15:37 UTC, nibra commented on extensions/UpperCase/config/extension.yml
> -            onBeforeRenderCompound: toUpperCase
Please also remove the test.

2016-09-27 15:37 UTC, nibra commented on extensions/Workflow/entities/StateEntity.xml
> +                   description="JFIELD_PARENT_DESC"
Also here: Just omit label and description.

2016-09-28 06:45 UTC, laoneo reviewed
Labels are omitted and test removed

2016-09-28 10:42 UTC, nibra approved these changes

2016-09-28 10:43 UTC, merged